//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fs.Binary.Codecs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fs.Binary.Codecs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alphabet must be exactaly {0} characters in length..
        /// </summary>
        internal static string AlphabetMustExactLength {
            get {
                return ResourceManager.GetString("AlphabetMustExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alphabet must contain at least one element in the array..
        /// </summary>
        internal static string AlphabetMustHaveAtleastOneElement {
            get {
                return ResourceManager.GetString("AlphabetMustHaveAtleastOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordinal value of all characters in the alphabet must be 127 or less..
        /// </summary>
        internal static string AlphabetOrdinalMustBeByte {
            get {
                return ResourceManager.GetString("AlphabetOrdinalMustBeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data contains a character that is not part of the encoding alphabet and is not considered an ignorable character..
        /// </summary>
        internal static string DecoderInvalidCharacter {
            get {
                return ResourceManager.GetString("DecoderInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data contains a padding character where a padding character is not allowed..
        /// </summary>
        internal static string DecoderInvalidPadding {
            get {
                return ResourceManager.GetString("DecoderInvalidPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encoded value is larger than the maximum possible value..
        /// </summary>
        internal static string DecoderOverflow {
            get {
                return ResourceManager.GetString("DecoderOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data does not end with the correct amount of padding..
        /// </summary>
        internal static string DecoderPaddingRequired {
            get {
                return ResourceManager.GetString("DecoderPaddingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A postfix is required, but the encoded data does not match any of the defined postfixes..
        /// </summary>
        internal static string DecoderPostfixRequired {
            get {
                return ResourceManager.GetString("DecoderPostfixRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A prefix is required, but the encoded data does not match any of the defined prefixes..
        /// </summary>
        internal static string DecoderPrefixRequired {
            get {
                return ResourceManager.GetString("DecoderPrefixRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last quantum of input appears to have been truncated..
        /// </summary>
        internal static string DecoderTruncatedQuantum {
            get {
                return ResourceManager.GetString("DecoderTruncatedQuantum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unused bits in the final quantum of data are not zero. The data may have been truncated..
        /// </summary>
        internal static string DecoderUnusedBitNonZero {
            get {
                return ResourceManager.GetString("DecoderUnusedBitNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance is read-only..
        /// </summary>
        internal static string InstanceIsReadOnly {
            get {
                return ResourceManager.GetString("InstanceIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string InvalidIndexCountLength {
            get {
                return ResourceManager.GetString("InvalidIndexCountLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from offset to the end of the source collection..
        /// </summary>
        internal static string InvalidOffsetCountLength {
            get {
                return ResourceManager.GetString("InvalidOffsetCountLength", resourceCulture);
            }
        }
    }
}
